### ISSUE TITLE
Implement UI for OONI Run v2 descriptor editor

### ISSUE THREAD

**Issue by hellais** [ooni/run#130]
This is about implementing the form which is needed for editing an OONI Run v2 descriptor. In an initial stage, since we may not have the backend implemented yet, we can just print to screen the raw JSON format of the specified descriptor.

For details on the full semantics of the OONI Run v2 descriptor see section "3.0 OONI Run descriptor" of the ooni-run-v2 spec document: https://github.com/ooni/spec/blob/master/backends/bk-005-ooni-run-v2.md

**Comment by hellais** [comment]
A first iteration of this is available here: https://github.com/ooni/run/pull/131

**Comment by hellais** [comment]
We have landed ooni/run#131 into a v2 branch and publish this branch to a dedicated domain for testing. All future iterations will be PRs targeting this staging branch.

**Comment by jbonisteel** [comment]
We will sync up with designer to understand changes

**Comment by majakomel** [comment]
I'm closing this issue since UI is implemented, follow up issues should be tracked under this epic: https://app.zenhub.com/workspaces/sprint-planning-5dfa4b7355438f7e86c80e5a/issues/gh/ooni/ooni.org/1538
