### ISSUE TITLE
Dockerize OONI Run

### ISSUE THREAD

**Issue by darkk** [ooni/run#14]
It should preferably run with read-only FS (maybe, with writable `/tmp`) and without `root` user even inside of the container.

That's needed to be able roll out (and roll-back) OONI Run without depending on state of external repositories and have "statically linked" bundle that can be easily managed as a separate "deployment unit".

Canonical image name is determined by [docker-build](https://github.com/ooni/sysadmin/blob/master/scripts/docker-build) script that also ensures that the image is built from clean git checkout and not from a working copy.

**Comment by hellais** [comment]
xref: https://github.com/ooni/sysadmin/issues/278

**Comment by hellais** [comment]
This is done.
