### ISSUE TITLE
OON Run v2: missing post-load toast from install link flow

### ISSUE THREAD

**Issue by jbonisteel** [ooni/run#148]
We seem to be missing the post-load toast from the UI for installing a new OONI run link. 

Here are the mockups that depict this: https://www.figma.com/file/G0MMzbEyAUEYpAgV9ZEzTC/OONI-Probe-Mobile-Android?type=design&node-id=1948-10037&mode=design&t=LmVyp5n5z5f4HSsC-0

**Comment by jbonisteel** [comment]
@aanorbel This currently looks different from the design - is that intentional? See screenshot.<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHdQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--146361dd94fa457074116874d32700978a73d344/Screenshot_20240326-104349.png" alt="Screenshot_20240326-104349.png" />

**Comment by aanorbel** [comment]
Yes this is intentional
