### ISSUE TITLE
OONI Run v2: Details not implemented in Link Updated flow 

### ISSUE THREAD

**Issue by jbonisteel** [ooni/run#155]
Expected Results: 

* When a Run v2 link is updated by the admin, the UI on the app should confirm to what we have outlined in the [Figma file ](https://www.figma.com/file/G0MMzbEyAUEYpAgV9ZEzTC/OONI-Probe-Mobile-Android?type=design&node-id=649-12341&mode=design&t=8ZoP1RIvM3mAeGTD-4)

Actual Results - there are a few things missing: 
- In the figma file there is a red 'updated' warning on the test detail view, that was not implemented 
- Also in the figma file, when a Run link needs to be updated, there should be the same red 'updated' warning on the dashboard - that did not appear
- I also don't see the previous revisions that were implemented in the figma file

**Comment by aanorbel** [comment]
@jbonisteel , should the red warning not say `Update available` when the descriptor needs an update and if we need to show `Updated` it should not be a warning but a green/success chip?

**Comment by jbonisteel** [comment]
@aanorbel I like you suggestion, but am unconcerned that 'Update available' would be long - let's implement what is in the Figma files for now.

**Comment by aanorbel** [comment]
@jbonisteel , to clarify, what is the condition of the `updated` chip. The language in the design an this issue doesn't make it clear to me if it is intended to show that

- The descriptor needs to be updated.
- The descriptor was recently updated.

With each case, the logic is very different.

**Comment by jbonisteel** [comment]
I just reviewed this again. Looking good, but a small nit-pik:

 <img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkh2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df840ad7a38227a952830393f992daf6b123886c/Screenshot_20240718-101041.png" alt="Screenshot_20240718-101041.png" />

The alignment of the red 'updated' banner looks off at the top of the screen. Likely not a release blocker

**Comment by jbonisteel** [comment]
Adding a screen recording of the crash 

https://github.com/user-attachments/assets/87e25d10-6e4d-4719-946c-bbefa08ad336

**Comment by jbonisteel** [comment]
The crash has been fixed
