### ISSUE TITLE
Run V2: Details missing when link is expired

### ISSUE THREAD

**Issue by jbonisteel** [ooni/run#161]
There are some details missing from the app UI and a run link has expired:

- When a link is expired, there should be an 'Expired' tag on the dashboard, as depicted in the [UI] (https://www.figma.com/file/G0MMzbEyAUEYpAgV9ZEzTC/OONI-Probe-Mobile-Android?type=design&node-id=303-6578&mode=design&t=H4XGMkwWFepRYIve-4)

- There should also be an 'Expired' tag on the [card](https://www.figma.com/file/G0MMzbEyAUEYpAgV9ZEzTC/OONI-Probe-Mobile-Android?type=design&node-id=305-6840&mode=design&t=H4XGMkwWFepRYIve-4)

- You should also be unable to run an Expired link. Currently, if you hit the 'Run' button on the dashboard, you can still select the expired link from the list of tests.

**Comment by aanorbel** [comment]
Hi @jbonisteel  please can you include the link you used for testing? I am using this link and see the expired card. https://run.test.ooni.org/v2/10010

I would say the missing component is that it still appears on the run test page.

|.|.|
|-|-|
| ![Screenshot_20240410_115010](https://github.com/ooni/run/assets/17911892/b62f1177-69da-438c-b322-bb26fc695ea6) | ![Screenshot_20240410_115020](https://github.com/ooni/run/assets/17911892/13c1f418-8bda-4602-9f2a-36ec14aee2b4) |

I link you used would be most helpful to reproduce and resolve any other issues if available.

**Comment by aanorbel** [comment]
Thanks. I see the problem now. We have different versions of the application.

|.|.|
|-|-|
| ![Screenshot_20240410_120633](https://github.com/ooni/run/assets/17911892/4bd97242-68f8-4455-b1e3-5554577bf0b5) | ![Screenshot_20240410_120653](https://github.com/ooni/run/assets/17911892/d74a7064-2355-43c9-bd6f-459fdd0c19d7) |

**Comment by jbonisteel** [comment]
Expired tag now appears properly. 

Note: you can, actually, install expired links. I don't think we ever discussed if that is desirable or not. 

At any rate, you cannot run an expired link.

**Comment by jbonisteel** [comment]
I am not sure what was happened or changed, but this issue is happening again. 

This is the Run link I am using: https://run.test.ooni.org/v2/10449 

But in the mobile app, the 'Expired' tag is missing (link to mockups: https://www.figma.com/design/G0MMzbEyAUEYpAgV9ZEzTC/OONI-Probe-Mobile-Android?node-id=303-6578&t=Orjd9JJjA6d2Gzcw-4). You can still run the test. 

I am using the build that is linked to from the Run channel on Slack: [https://appdistribution.firebase.google.com/testerapps/1:951667061699:android:13ca15ecce8c0f15[…]/releases/6iuiq6liv1at0?utm_source=firebase-console](https://appdistribution.firebase.google.com/testerapps/1:951667061699:android:13ca15ecce8c0f15374376/releases/6iuiq6liv1at0?utm_source=firebase-console)
![Screenshot_20240806-105559](https://github.com/user-attachments/assets/97480b6b-1815-48a2-ba60-c66f2f691cf4)

**Comment by aanorbel** [comment]
![Screenshot_20240806-165740.png](https://github.com/user-attachments/assets/f8cf5f9a-1792-47cd-9ca0-1bd98e8da603)

![Screenshot_20240806-165736.png](https://github.com/user-attachments/assets/015871d6-d21d-442c-9ff5-2f81ee29b7ff)

Please update close the app and open again. This will ensure the latest updates are fetched from the server.

**Comment by jbonisteel** [comment]
Confirmed this is still an issue, testing this link: https://run.test.ooni.org/v2/10451 

I opened up the app today and while the link is expired on the web, it is not expired on the app.
![Screenshot_20240809-063927](https://github.com/user-attachments/assets/0047fb74-7753-43fb-bd37-19556ea1fd76)

**Comment by aanorbel** [comment]
Taking another look at this.

**Comment by jbonisteel** [comment]
![Screenshot_20240809-070000](https://github.com/user-attachments/assets/5b5c039a-053a-40e8-9742-0a7ca19e328d)
