### ISSUE TITLE
Run v2: Updated tag still appears after updating a link

### ISSUE THREAD

**Issue by jbonisteel** [ooni/run#188]
- I have been testing this link: https://run.test.ooni.org/v2/10441
- Disabled auto-updates
- Made a change to the link
- Revisit the app and go through process to install updates
- The red 'updated' tag still appears on the dashboard and the detail view, even though updates have been installed. If I force-stop the app and reopen it, the updated tag will go away. 
- Also the updated tag doesn't look aligned on the detail view 

![Screenshot_20240806-111649](https://github.com/user-attachments/assets/a5c598c7-9009-41de-93f7-20069012b9e1)

**Comment by aanorbel** [comment]
Hi @jbonisteel , I am unable to reproduce this error.

[Screen_recording_20240807_181303.webm](https://github.com/user-attachments/assets/ed299fc5-56a5-4786-b0f9-1f9bfa72cec0)

**Comment by jbonisteel** [comment]
This is fixed now
