### ISSUE TITLE
Run v2: numbered lists are not supported in the description

### ISSUE THREAD

**Issue by sloncocs** [ooni/run#204]
If a numbered list is added to the description section, the numbers do not appear on the created page. 

The description section while editing the link description: 
<img width="886" alt="Screenshot 2024-11-13 at 17 17 17" src="https://github.com/user-attachments/assets/4368a259-0829-401d-8d47-a3a3a3da8332">

The same section but published within a link: 
<img width="809" alt="Screenshot 2024-11-13 at 17 36 37" src="https://github.com/user-attachments/assets/856aa9d7-9600-4c2d-9e42-69159bef6322">

The described link: https://run.ooni.org/v2/10051

**Comment by majakomel** [comment]
Fixed in https://github.com/ooni/design-system/commit/df063161cf07f8d3cf0b84d0cb435106424e00f0 and https://github.com/ooni/run/commit/77c5a8f49671b72b4a3a3cf7e11cfc5cbc1a95d5
