### ISSUE TITLE
Create OONI run buttons of interesting measurements

### ISSUE THREAD

**Issue by anadahz** [ooni/run#25]
OONI run should provide an UI way of adding highlighted or previous generated OONI run links that could be reused for people that would like to reproduce measurements of other entities. Some examples include OONI run link buttons of all Wikipedia domains or a list of Tor directory authorities web servers.

This issue is based upon discussions on sessions occurred during IFF.

**Comment by hellais** [comment]
We have added such OONI Run buttons to our website in the get-involved Run section: https://ooni.org/get-involved/run/
