### ISSUE TITLE
The input bar is very laggy

### ISSUE THREAD

**Issue by hellais** [ooni/run#26]
Normally the URL input is pretty laggy, but it gets even more laggy if you try to copy paste a single URL into the box to the point that it becomes unsuable unless refreshing.

I have noticed this happening on macOS with Chromium Version 75.0.3738.0 (Developer Build) (64-bit).

The input is especially laggy on mobile to the point that it's basically unusable.

**Comment by hellais** [comment]
Already upgrading next helps, see: https://github.com/ooni/run/pull/27.

Some more upgrade issues need to be dealt with though first.

**Comment by xhdix** [comment]
Do you really need 52830 lines of JS code with recursive algorithms?

![image](https://user-images.githubusercontent.com/12384263/70167384-acbbf400-16d7-11ea-8804-03e22ff53fc0.png)

**Comment by hellais** [comment]
@sarathms has tried to debug this and deployed a new version, but is not able to reproduce it.

**Comment by xhdix** [comment]
Current version on site?
![image](https://user-images.githubusercontent.com/12384263/72748570-a7076880-3bc8-11ea-88d6-8b66b0e17cb7.png)

![image](https://user-images.githubusercontent.com/12384263/72748558-a078f100-3bc8-11ea-8f55-697db1cc9258.png)

**Comment by hellais** [comment]
This has been fixed since the rewrite of the input form with react-forms. This issue can be closed.
