### ISSUE TITLE
Make it possible to add annotations or labels to OONI Run link lists

### ISSUE THREAD

**Issue by hellais** [ooni/run#28]
It would be nice if people creating OONI Run links could add an annotation to the measurements so that it's possible to search by them in the API and we can mine these lists to feed into the test-lists.

This was suggested by @pellaeon

**Comment by lorenzoPrimi** [comment]
Done months ago.
Ref:
https://github.com/ooni/probe-ios/blob/master/ooniprobe/Test/Test/AbstractTest.m#L60
https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/activity/OoniRunActivity.java#L195

**Comment by lorenzoPrimi** [comment]
Reopening as it might be needed for desktop

**Comment by hellais** [comment]
I guess we also need support for generating these sorts of links inside of the OONI Run web interface.

@lorenzoPrimi can you share an example OONI Run link with a custom annotation?

**Comment by lorenzoPrimi** [comment]
I added the code in the previous comment. We add a "ooni-run" annotation in every test that is run with OONI Run

**Comment by hellais** [comment]
Ah ok, that's good, yet this issue is about adding support for adding custom annotations via OONI Run links. So that a user would go to run.ooni.io and say "I want to add my custom annotation called 'my_custom_name: 'bar'" and then the app knows how to interpret that.
