### ISSUE TITLE
Links work oddly inside of Facebook Messenger

### ISSUE THREAD

**Issue by bassosimone** [ooni/run#36]
This is kinda known, but I feel like it's good anyway to post it here. I wrote a number of run.ooni.io links to a OONI colleague on Facebook Messanger. Upon clicking on the links, the app was not opened, and instead I was directed on run.ooni.io. There, I could click on a button to run the test successfully.

I guess this is okay for a first release, because the functionality is there. What is a bit annoying is that you need to click twice. To confirm you're sure you want to leave Facebook Messenger and to confirm that you want to allow Facebook Messenger to open ooniprobe.

**Comment by hellais** [comment]
I think we should do some testing of this as part of the OONI Run improvement work.

Adding it to that epic.
