### ISSUE TITLE
Remove all other tests beyond Web Connectivity from the generate page

### ISSUE THREAD

**Issue by hellais** [ooni/run#42]
Consider dropping anything beyond the website testing (eg. Performance, Middlebox, etc.) capability in OONI Run links (ask this in the usability study).

**Comment by agrabeli** [comment]
@hellais I think this needs to be assigned to @sarathms ?

**Comment by hellais** [comment]
Yes you are right. I have done that.

**Comment by sarathms** [comment]
This basically makes the sidebar obsolete, which makes the page look like this now. 
![image.png](https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/aec4bffe-5ef1-4369-a219-6e07f93268a8)

@agrabeli @hellais Do you guys think the page needs any additional information to make up for the loss of a relevant part of the sidebar?
![image.png](https://images.zenhubusercontent.com/5defc00b8c6ab2dae53692c4/a11edd1a-9f23-4bb3-aafe-d10766e1bdc8)
