### ISSUE TITLE
Improve UI of ooni-run

### ISSUE THREAD

**Issue by hellais** [ooni/run#5]
@elioqoshi says on slack:

- [ ] Move the X close button a bit more to the left and downwards (so it is on the same line as "Your link is ready" I'd say.
- [x] Reduce padding of all elements in the modal menu
- [ ] Remove the 2 first empty lines in the code output field

**Comment by bassosimone** [comment]
@hellais would it make sense to also include #7 as part of this revamping?

**Comment by hellais** [comment]
I think these are two separate issues. The things listed in here are quick fixes, #7 is a full new feature (that requires also some thinking in terms of what is the best solution).

**Comment by majakomel** [comment]
Closing this issue since it's outdated by now.
