### ISSUE TITLE
Improve performance of OONI Run website

### ISSUE THREAD

**Issue by agrabeli** [ooni/run#59]
Several community members mentioned that the OONI Run website (run.ooni.io) lags and that they find the process of typing URLs into the URL slots slow and sluggish. 

More specifically, they mentioned that there is a delay between typing and the typed letters being displayed in the URL slots of the OONI Run website.

**Comment by hellais** [comment]
This might have already been done. @sarathms can you confirm?

**Comment by sarathms** [comment]
Yes we can close this. We have already documented further improvements in other issues.
