### ISSUE TITLE
Default to setting the URL prefix to "https://"

### ISSUE THREAD

**Issue by agrabeli** [ooni/run#61]
Currently, the URL slots in the OONI Run platform include the HTTP prefix, but to new users, it may not be clear/obvious that they should manually change the prefix to HTTPS (if that is what is supported for the website they want to test).

**Comment by hellais** [comment]
We should change the default field to be `https://` as most websites support https anyways and it's easier to remove a character than add it.

**Comment by hellais** [comment]
This is implemented inside of: https://github.com/ooni/run/pull/74
