### ISSUE TITLE
Certain OONI Run links will break the Ooni Probe App When Trying to view results. 

### ISSUE THREAD

**Issue by misuki74** [ooni/run#69]
Coming from the workshop yesterday

At first, I thought it's probably a bug in my OONI app, but seems to be the bug is reproducible. 

Other group link: https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2[…]sysam.com%22%2C%22http%3A%2F%2Fwww.camldp.org%22%5D%7D&mv=1.2.0

My group's link: https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22-%22%2C%2[…]2%2C%22https%3A%2F%2Fwww.cambodiadaily.com%2F%22%5D%7D&mv=1.2.0
(try running this and view results, if you get a crash)

So you run the test using both links, but for my group, you'll crash the app, when you try to view the result.

Here're some details about my phone. 

Samsung Galaxy S10 SM G973F/DS

![image](https://user-images.githubusercontent.com/66195613/124701554-62d56880-df21-11eb-8660-af3588ef6347.png)
![Screenshot_20210707-122130_Settings](https://user-images.githubusercontent.com/66195613/124701565-67018600-df21-11eb-89f5-28224bbbb92e.jpg)

**Comment by hellais** [comment]
Thanks for reporting this bug and for sharing detailed device information. We have created an issue for tracking it over here: https://github.com/ooni/probe/issues/1706.

**Comment by lorenzoPrimi** [comment]
This has been already fixed, please try with the app version 3.2.0
