### ISSUE TITLE
Bug when copying and pasting URLs

### ISSUE THREAD

**Issue by rayasharbain** [ooni/run#82]
When entering URLs for testing via copy and paste (either via keyboard shortcuts or mouse right-click), all previous URLs are erased and only the last one entered remains. The only way to counter the issue is to type the URLs letter-by-letter.

This issue is present on desktop and mobile browsers, I am using Firefox on both.

Video attached replicates the bug on a mobile browser.

https://user-images.githubusercontent.com/25263499/146670604-da684b51-cabe-403a-85d1-eaaacb4933aa.mp4

**Comment by hellais** [comment]
Thanks for reporting this issue. I can confirm that it's indeed possible to reproduce this.

I suspect this has something to do with the fact that we support copy pasting many lines of URLs, but this goes in conflict with copy pasting an individual URL.

This is quite a high priority issue to resolve.
