### ISSUE TITLE
Include example of URL format in OONI Run page

### ISSUE THREAD

**Issue by agrabeli** [ooni/run#92]
During the OONI Partner Training 2021, participants mentioned that it would be helpful if the first URL slot in the OONI Run page included an example of a URL format (e.g. `https://www.facebook.com/`) so that they could get a better idea of what to add in the URL slots.

**Comment by thara003** [comment]
I would like to work on the issue, the issue still up?

**Comment by agrabeli** [comment]
Thank you @thara003 ! <3

@sarathms yep, I think it would be great to include a placeholder (like the example you share) with `https://twitter.com/` in the first URL slot.
