### ISSUE TITLE
Improve OONI Run performance on mobile browsers

### ISSUE THREAD

**Issue by agrabeli** [ooni/run#96]
During the OONI Partner Training 2021, participants mentioned that it's hard to generate OONI Run links through mobile browsers because the experience is slow and sluggish. We should probably look into this and make improvements.

**Comment by hellais** [comment]
Is this still the case? I believe that since the training was done we have upgraded the code used for the input form and the performance on mobile has significantly improved.

I am going to close this and suggest reopening it if it's still the case.
